name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4

      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Installing dependencies
        run: npm install

      - name: Lint the code
        run: npm run lint

      - name: Build the project
        run: npm run build

      - name: Check SSH key
        run: |
          if [ -z "${{ secrets.VPS_SSH_KEY }}" ]; then
            echo "SSH key is not set. Please set the VPS_SSH_KEY secret in your repository settings."
            exit 1
          fi

      - name: Clean remote folder
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            rm -rf /var/www/mitermitek-front/*

      - name: Upload to VPS
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: 'dist'
          target: '/var/www/mitermitek-front'
          strip_components: 1
